---
- name: PLAY 1 - Create VRFs
  hosts: ios_routers

  tasks:
    
    - name: TASK 1 - Create VRFs on PE routers
      cisco.ios.ios_config:
        src: templates/ios_vpns.j2
        save_when: changed
      register: config_changes
      notify: config_changed


  handlers:
    
    - name: HANDLER 1 - Print config changes if any changes on routers have been made
      ansible.builtin.debug:
        msg: "{{ config_changes }}"
      listen: config_changed
