---
- name: PLAY 1 - Configure VRFs with ios_vrf module
  hosts: ios_routers

  tasks:

    - name: TASK 1 - Create VRFs
      cisco.ios.ios_vrf:
        vrfs: "{{ vrfs }}"
      notify: config_changed
      register: config_changes

  handlers:

    - name: HANDLER 1 - Print configuration changes
      ansible.builtin.debug:
        msg: "{{ config_changes }}"
      listen: config_changed

    - name: HANDLER 2 - Save configuration to startup-config
      cisco.ios.ios_command:
        commands: 
          - "write memory"
      listen: config_changed
