---
- name: PLAY - Parse Cisco router config with cli_parse module 
  hosts: routers
  connection: network_cli
  gather_facts: no
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:

    - name: TASK - Get 'show version' info and parse it
      ansible.utils.cli_parse:
        command: "show version"
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: show_ver_data

    - name: TASK - Print parsed 'show version' info
      ansible.builtin.debug:
        msg: "{{ show_ver_data }}"

# The following two tasks fail - NTC templates can't correctly parse "show vrf detail"
    - name: TASK - Get 'show vrf detail' info and parse it
      ansible.utils.cli_parse:
        command: "show vrf detail"
        parser:
          name: ansible.netcommon.ntc_templates
        set_fact: show_vrf_data

    - name: TASK - Print parsed 'show vrf detail' info
      ansible.builtin.debug:
        msg: "{{ show_vrf_data }}"


